- apps/dashboard/features/dao-overview/components/ProgressBar.tsx
- apps/dashboard/features/dao-overview/components/SecurityCouncilCard.tsx
> fix:  progress-warning bar - dao-overview

- apps/dashboard/features/governance-activity/GovernanceActivitySection.tsx
- apps/dashboard/shared/constants/sections-constants.ts
> fix: make 1 year the default time interval

- apps/dashboard/features/dao-overview/components/QuorumCard.tsx
- apps/dashboard/shared/dao-config/ens.ts
- apps/dashboard/shared/dao-config/types.ts
- apps/dashboard/shared/dao-config/uni.ts
Uni has logic as `For`, but it's being shown `For + Abstain`. This PR then moves this logic to the DAO config structure so each DAO has its own.
> Logic from DAO config

- apps/indexer/src/lib/event-handlers.ts
> fix: update votingPowerHistory avoid PK conflict

- apps/indexer/ponder.schema.ts
- apps/indexer/src/eventHandlers/delegation.ts
> feat: delta on `votingPowerHistory`

- apps/dashboard/app/donate/page.tsx
- apps/dashboard/app/faq/page.tsx
- apps/dashboard/app/glossary/page.tsx
- apps/dashboard/shared/components/buttons/BottomNavigationButtons.tsx
- apps/dashboard/shared/components/index.ts
- apps/dashboard/shared/constants/sections-constants.ts
- apps/dashboard/widgets/HeaderDAOSidebar.tsx
- apps/dashboard/widgets/HeaderSidebar.tsx
- apps/graphql-client/generated.ts
- apps/graphql-client/types.ts
> 1044 - Additional Pages Navigation

- apps/api-gateway/package.json
- apps/dashboard/package.json
- apps/indexer-metrics/package.json
- apps/indexer/package.json
- package.json
- packages/graphql-client/package.json
- packages/local-node/package.json
- turbo.json
Clean script removes all the `node_modules` and generated files to start the repo fresh.
> Clean script

- apps/dashboard/features/holders-and-delegates/components/ProposalsTable.tsx
- apps/dashboard/shared/components/tables/TheTable.tsx
- apps/indexer/src/api/repositories/proposals-activity.repository.ts
feat: Adding blank slate on empty table;
> fix: Fixing the vote timing sorting;

- apps/dashboard/features/holders-and-delegates/components/DelegateProposalsActivity.tsx
- apps/dashboard/features/holders-and-delegates/utils/proposalsTableUtils.tsx
> fix: proposal end result and voting label

- .eslintignore
- .husky/pre-commit
- .vscode/launch.json
- apps/dashboard/features/holders-and-delegates/components/DelegateDelegationHistoryTable.tsx
- apps/dashboard/features/holders-and-delegates/components/DelegateProposalsActivity.tsx
- apps/dashboard/features/holders-and-delegates/components/ProposalsTable.tsx
- apps/dashboard/features/holders-and-delegates/hooks/useDelegateDelegationHistory.ts
- apps/dashboard/shared/dao-config/ens.ts
- apps/dashboard/shared/dao-config/uni.ts
- apps/indexer/package.json
- apps/indexer/ponder.schema.ts
- apps/indexer/src/api/controller/proposals-activity.controller.ts
- apps/indexer/src/api/repositories/proposals-activity.repository.ts
- apps/indexer/src/api/services/proposals-activity/proposals-activity.service.ts
- apps/indexer/src/eventHandlers/delegation.ts
- apps/indexer/src/eventHandlers/transfer.ts
- apps/indexer/src/eventHandlers/voting.ts
- compose.yaml
- package.json
- packages/graphql-client/generated.ts
- packages/graphql-client/types.ts
- pnpm-lock.yaml
The PK of the voting_onchain table was the `txHash` which was causing a conflict when multiple votes were casted on the same transaction
> Data Table fixes

- apps/indexer/src/eventHandlers/delegation.ts
> Ignore account balance not found

- apps/dashboard/shared/dao-config/op.ts
- apps/dashboard/shared/dao-config/uni.ts
> Enable UNI data tables

- .github/workflows/deploy-indexer.yaml
- apps/indexer/package.json
> Prune inactive db schema CI

- apps/dashboard/features/risk-analysis/RiskAnalysisSection.tsx
- apps/dashboard/features/show-support/components/CardDaoSignature.tsx
- apps/dashboard/features/show-support/components/ShowYourSupportStickyBar.tsx
- apps/dashboard/shared/constants/sections-constants.ts
> chore: fix gramatical erros

- apps/api-gateway/src/resolvers/rest.ts
> fix: add proposal rest endpoint to gateway redirect

- .github/workflows/deploy-indexer.yaml
> chore: disable db prune on ci

- apps/indexer/src/api/index.ts
- **chore: disable db prune on ci**
- **chore: disable total assets dune request**
> Disable total assets request

- apps/indexer/src/api/index.ts
> chore: enable total assets dune request

- apps/dashboard/shared/dao-config/gtc.ts
- **feat: Adding indexing for gitcoin;**
- **removing unused import;**
- **feat: adding gitcoin config and icon;**
- **feat: adding gitcoin in the sidebar dropdown;**
- **feat: completed last update endpoint, returns the last update date for each chart;**
- **fix: fix build;**
- **fix: fix build, add gitcoin og;**
- **fix: gitcoin governor contract address**
- **fix: governor base implements interface**
- **fix: quorum call**
- **fix: gtc governor event arguments**
- **Update apps/indexer/src/indexer/gtc/governor.ts**
- **fix: fixing build;**
- **fix: fix coingecko dao enum; fix: fixing status code of historical token data endpoint;**
- **fix: fixing PR comments;**
- **Update apps/indexer/src/api/repositories/last-update.repository.ts**
- **Update …
> GTC Risk level

- apps/api-gateway/schema.graphql
- apps/indexer/ponder.schema.ts
- apps/indexer/src/api/mappers/transactions.ts
- apps/indexer/src/api/repositories/transactions.repository.ts
- apps/indexer/src/api/services/transactions/transactions.service.ts
- apps/indexer/src/indexer/gtc/erc20.ts
- packages/graphql-client/generated.ts
- packages/graphql-client/types.ts
fix: adding index for transfers and delegations, to optimize the query;
feat: handling transactions on gitcoin
> fix: removing total transactions from endpoint;

- .github/workflows/deploy-indexer.yaml
- apps/indexer/src/api/index.ts
only trigger indexer deploy when actual indexer files have been changed. avoid redeploying on API changes
> CI Watch Path
